//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAAMEN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int RamenId { get; set; }
        public string RamenName { get; set; }
        public int Quantity { get; set; }
        public string RamenStatus { get; set; }
    
        public virtual Raman Raman { get; set; }
    }
}
